### ISSUE TITLE
Can v_P (vim 8.2.4881) be repeated?

### ISSUE THREAD

**Issue by kiryph** [inkarkat/vim-visualrepeat#1]
Vim has introduced `v_P` in version 8.2.4881.

https://vimhelp.org/change.txt.html#v_P

I would like to dot repeat this. 

Could vim-visualrpeat support this?

**Comment by inkarkat** [comment]
Yes, you could build such a mapping with the plugin. (Actually, I'm a bit surprised that Vim doesn't offer repetition for that out of the box. You may suggest such at the [bug tracker](https://github.com/vim/vim/issues), or directly discuss this on the [vim_dev mailing list](https://www.vim.org/community.php).)

Alternatively, my [ReplaceWithRegister plugin](http://www.vim.org/scripts/script.php?script_id=2703) precedes that mapping and offers a `{Visual}gr` mapping that is repeatable (via _visualrepeat_).

**Comment by kiryph** [comment]
> Yes, you could build such a mapping with the plugin

How would this be done?

> Alternatively, my [ReplaceWithRegister plugin](http://www.vim.org/scripts/script.php?script_id=2703) precedes that mapping and offers a {Visual}gr mapping that is repeatable (via visualrepeat).

I am actually a long time user of ReplaceWithRegister and still cannot live without it. Here a big thanks to you for this very helpful plugin.

[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) setup suggests (as many others) to use `gr` for finding references of symbols (the constant battle for free normal mode mappings).
I was wondering, whether I could start using `v_P` to not rely on ReplaceWithRegister. However, I doubt that. I really like the operator workflow of ReplaceWithRegister without visual mode.  I guess I use `gr` from ReplaceWithRegister more often than the normal `p`.
